print("##############################")
print("#                            #")
print("#    Arya Arrozza Ridho S    #")
print("#        2410817210010       #")
print("#                            #")
print("##############################")